spring:
  profiles:
    active: dev
  datasource:
    initial-size: 5
    max-active: 20
    
pagehelper:
  autoDialect: true
  closeConn: true
  pageSizeZero: true
  
server:
  session.timeout: 900
  context-path: /ymcake
  port: 8080
  
wx:
  appId: wxf16b6adb67d33eee
  appSecret: ba312ecea840ec4eb46e5e5f626327c1
  oauthUrl: https://api.weixin.qq.com/sns/jscode2session

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/owcake?useSSL=false
    username: owcake
    password: Pass1234
    
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.119.1:3306/owcake?useSSL=false
    username: owcake
    password: 2wsx#EDC
    
server:
  port: 443
  ssl:
    key-store: classpath:troytan1991.club.pfx
    key-store-password: 4nh0hc1eabd49
    keyStoreType: PKCS12