package com.troytan.ymcake.domain;

import java.util.Date;

public class Addr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.ADDR_ID
     *
     * @mbg.generated
     */
    private Long addrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.receiver
     *
     * @mbg.generated
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.created_on
     *
     * @mbg.generated
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.updated_on
     *
     * @mbg.generated
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.USER_ID
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.AREA_ID
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.is_default
     *
     * @mbg.generated
     */
    private Boolean isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_addr.area_str
     *
     * @mbg.generated
     */
    private String areaStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.ADDR_ID
     *
     * @return the value of tt_addr.ADDR_ID
     *
     * @mbg.generated
     */
    public Long getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.ADDR_ID
     *
     * @param addrId the value for tt_addr.ADDR_ID
     *
     * @mbg.generated
     */
    public void setAddrId(Long addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.receiver
     *
     * @return the value of tt_addr.receiver
     *
     * @mbg.generated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.receiver
     *
     * @param receiver the value for tt_addr.receiver
     *
     * @mbg.generated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.phone
     *
     * @return the value of tt_addr.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.phone
     *
     * @param phone the value for tt_addr.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.detail
     *
     * @return the value of tt_addr.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.detail
     *
     * @param detail the value for tt_addr.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.created_on
     *
     * @return the value of tt_addr.created_on
     *
     * @mbg.generated
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.created_on
     *
     * @param createdOn the value for tt_addr.created_on
     *
     * @mbg.generated
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.created_by
     *
     * @return the value of tt_addr.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.created_by
     *
     * @param createdBy the value for tt_addr.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.updated_on
     *
     * @return the value of tt_addr.updated_on
     *
     * @mbg.generated
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.updated_on
     *
     * @param updatedOn the value for tt_addr.updated_on
     *
     * @mbg.generated
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.updated_by
     *
     * @return the value of tt_addr.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.updated_by
     *
     * @param updatedBy the value for tt_addr.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.USER_ID
     *
     * @return the value of tt_addr.USER_ID
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.USER_ID
     *
     * @param userId the value for tt_addr.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.AREA_ID
     *
     * @return the value of tt_addr.AREA_ID
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.AREA_ID
     *
     * @param areaId the value for tt_addr.AREA_ID
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.is_default
     *
     * @return the value of tt_addr.is_default
     *
     * @mbg.generated
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.is_default
     *
     * @param isDefault the value for tt_addr.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_addr.area_str
     *
     * @return the value of tt_addr.area_str
     *
     * @mbg.generated
     */
    public String getAreaStr() {
        return areaStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_addr.area_str
     *
     * @param areaStr the value for tt_addr.area_str
     *
     * @mbg.generated
     */
    public void setAreaStr(String areaStr) {
        this.areaStr = areaStr == null ? null : areaStr.trim();
    }
}