package com.troytan.ymcake.domain;

import java.util.Date;

public class Delivery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    private Long deliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.delivery_no
     *
     * @mbg.generated
     */
    private String deliveryNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.delivery_company
     *
     * @mbg.generated
     */
    private String deliveryCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.ADDR_ID
     *
     * @mbg.generated
     */
    private Long addrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.type
     *
     * @mbg.generated
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.receive_time
     *
     * @mbg.generated
     */
    private Date receiveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.DELIVERY_ID
     *
     * @return the value of tt_delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    public Long getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.DELIVERY_ID
     *
     * @param deliveryId the value for tt_delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    public void setDeliveryId(Long deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.delivery_no
     *
     * @return the value of tt_delivery.delivery_no
     *
     * @mbg.generated
     */
    public String getDeliveryNo() {
        return deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.delivery_no
     *
     * @param deliveryNo the value for tt_delivery.delivery_no
     *
     * @mbg.generated
     */
    public void setDeliveryNo(String deliveryNo) {
        this.deliveryNo = deliveryNo == null ? null : deliveryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.delivery_company
     *
     * @return the value of tt_delivery.delivery_company
     *
     * @mbg.generated
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.delivery_company
     *
     * @param deliveryCompany the value for tt_delivery.delivery_company
     *
     * @mbg.generated
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany == null ? null : deliveryCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.ADDR_ID
     *
     * @return the value of tt_delivery.ADDR_ID
     *
     * @mbg.generated
     */
    public Long getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.ADDR_ID
     *
     * @param addrId the value for tt_delivery.ADDR_ID
     *
     * @mbg.generated
     */
    public void setAddrId(Long addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.type
     *
     * @return the value of tt_delivery.type
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.type
     *
     * @param type the value for tt_delivery.type
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.receive_time
     *
     * @return the value of tt_delivery.receive_time
     *
     * @mbg.generated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.receive_time
     *
     * @param receiveTime the value for tt_delivery.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }
}