package com.troytan.ymcake.domain;

import java.util.Date;

public class Delivery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    private Long deliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.delivery_no
     *
     * @mbg.generated
     */
    private String deliveryNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.delivery_company
     *
     * @mbg.generated
     */
    private String deliveryCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.ADDR_ID
     *
     * @mbg.generated
     */
    private Long addrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.deliver_method
     *
     * @mbg.generated
     */
    private Short deliverMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.deliver_date
     *
     * @mbg.generated
     */
    private Date deliverDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_delivery.deliver_time
     *
     * @mbg.generated
     */
    private String deliverTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.DELIVERY_ID
     *
     * @return the value of tt_delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    public Long getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.DELIVERY_ID
     *
     * @param deliveryId the value for tt_delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    public void setDeliveryId(Long deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.delivery_no
     *
     * @return the value of tt_delivery.delivery_no
     *
     * @mbg.generated
     */
    public String getDeliveryNo() {
        return deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.delivery_no
     *
     * @param deliveryNo the value for tt_delivery.delivery_no
     *
     * @mbg.generated
     */
    public void setDeliveryNo(String deliveryNo) {
        this.deliveryNo = deliveryNo == null ? null : deliveryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.delivery_company
     *
     * @return the value of tt_delivery.delivery_company
     *
     * @mbg.generated
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.delivery_company
     *
     * @param deliveryCompany the value for tt_delivery.delivery_company
     *
     * @mbg.generated
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany == null ? null : deliveryCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.ADDR_ID
     *
     * @return the value of tt_delivery.ADDR_ID
     *
     * @mbg.generated
     */
    public Long getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.ADDR_ID
     *
     * @param addrId the value for tt_delivery.ADDR_ID
     *
     * @mbg.generated
     */
    public void setAddrId(Long addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.deliver_method
     *
     * @return the value of tt_delivery.deliver_method
     *
     * @mbg.generated
     */
    public Short getDeliverMethod() {
        return deliverMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.deliver_method
     *
     * @param deliverMethod the value for tt_delivery.deliver_method
     *
     * @mbg.generated
     */
    public void setDeliverMethod(Short deliverMethod) {
        this.deliverMethod = deliverMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.deliver_date
     *
     * @return the value of tt_delivery.deliver_date
     *
     * @mbg.generated
     */
    public Date getDeliverDate() {
        return deliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.deliver_date
     *
     * @param deliverDate the value for tt_delivery.deliver_date
     *
     * @mbg.generated
     */
    public void setDeliverDate(Date deliverDate) {
        this.deliverDate = deliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_delivery.deliver_time
     *
     * @return the value of tt_delivery.deliver_time
     *
     * @mbg.generated
     */
    public String getDeliverTime() {
        return deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_delivery.deliver_time
     *
     * @param deliverTime the value for tt_delivery.deliver_time
     *
     * @mbg.generated
     */
    public void setDeliverTime(String deliverTime) {
        this.deliverTime = deliverTime == null ? null : deliverTime.trim();
    }
}