package com.troytan.ymcake.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.ORDER_ID
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.delivery_fee
     *
     * @mbg.generated
     */
    private BigDecimal deliveryFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.created_on
     *
     * @mbg.generated
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.updated_on
     *
     * @mbg.generated
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.delivery_no
     *
     * @mbg.generated
     */
    private String deliveryNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_order.delivery_company
     *
     * @mbg.generated
     */
    private String deliveryCompany;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.ORDER_ID
     *
     * @return the value of tt_order.ORDER_ID
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.ORDER_ID
     *
     * @param orderId the value for tt_order.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.status
     *
     * @return the value of tt_order.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.status
     *
     * @param status the value for tt_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.price
     *
     * @return the value of tt_order.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.price
     *
     * @param price the value for tt_order.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.delivery_fee
     *
     * @return the value of tt_order.delivery_fee
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryFee() {
        return deliveryFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.delivery_fee
     *
     * @param deliveryFee the value for tt_order.delivery_fee
     *
     * @mbg.generated
     */
    public void setDeliveryFee(BigDecimal deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.created_on
     *
     * @return the value of tt_order.created_on
     *
     * @mbg.generated
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.created_on
     *
     * @param createdOn the value for tt_order.created_on
     *
     * @mbg.generated
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.created_by
     *
     * @return the value of tt_order.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.created_by
     *
     * @param createdBy the value for tt_order.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.updated_on
     *
     * @return the value of tt_order.updated_on
     *
     * @mbg.generated
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.updated_on
     *
     * @param updatedOn the value for tt_order.updated_on
     *
     * @mbg.generated
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.updated_by
     *
     * @return the value of tt_order.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.updated_by
     *
     * @param updatedBy the value for tt_order.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.delivery_no
     *
     * @return the value of tt_order.delivery_no
     *
     * @mbg.generated
     */
    public String getDeliveryNo() {
        return deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.delivery_no
     *
     * @param deliveryNo the value for tt_order.delivery_no
     *
     * @mbg.generated
     */
    public void setDeliveryNo(String deliveryNo) {
        this.deliveryNo = deliveryNo == null ? null : deliveryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_order.delivery_company
     *
     * @return the value of tt_order.delivery_company
     *
     * @mbg.generated
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_order.delivery_company
     *
     * @param deliveryCompany the value for tt_order.delivery_company
     *
     * @mbg.generated
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany == null ? null : deliveryCompany.trim();
    }
}