package com.troytan.ymcake.domain;

public class ProductOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_product_order.ORDER_ID
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_product_order.PRODUCT_ID
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_product_order.count
     *
     * @mbg.generated
     */
    private Short count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_product_order.SIZE_ID
     *
     * @mbg.generated
     */
    private Long sizeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_product_order.ORDER_ID
     *
     * @return the value of tr_product_order.ORDER_ID
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_product_order.ORDER_ID
     *
     * @param orderId the value for tr_product_order.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_product_order.PRODUCT_ID
     *
     * @return the value of tr_product_order.PRODUCT_ID
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_product_order.PRODUCT_ID
     *
     * @param productId the value for tr_product_order.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_product_order.count
     *
     * @return the value of tr_product_order.count
     *
     * @mbg.generated
     */
    public Short getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_product_order.count
     *
     * @param count the value for tr_product_order.count
     *
     * @mbg.generated
     */
    public void setCount(Short count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_product_order.SIZE_ID
     *
     * @return the value of tr_product_order.SIZE_ID
     *
     * @mbg.generated
     */
    public Long getSizeId() {
        return sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_product_order.SIZE_ID
     *
     * @param sizeId the value for tr_product_order.SIZE_ID
     *
     * @mbg.generated
     */
    public void setSizeId(Long sizeId) {
        this.sizeId = sizeId;
    }
}