package com.troytan.ymcake.repository;

import com.troytan.ymcake.domain.Delivery;
import com.troytan.ymcake.dto.DeliveryDto;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DeliveryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_delivery
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long deliveryId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_delivery
     *
     * @mbg.generated
     */
    int insert(Delivery record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_delivery
     *
     * @mbg.generated
     */
    Delivery selectByPrimaryKey(Long deliveryId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_delivery
     *
     * @mbg.generated
     */
    List<Delivery> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_delivery
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Delivery record);

    void updateByOrderId(@Param("orderId") Long orderId, @Param("deliver") DeliveryDto deliveryDto);
}
