package com.troytan.ymcake.repository;

import com.troytan.ymcake.domain.FitmentDetail;
import java.util.List;

public interface FitmentDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fiementDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    int insert(FitmentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    FitmentDetail selectByPrimaryKey(Integer fiementDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    List<FitmentDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_fitment_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FitmentDetail record);
}