package com.troytan.ymcake.repository;

import com.troytan.ymcake.domain.Order;
import com.troytan.ymcake.vo.OrderVo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OrderMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    void updateStatusById(@Param("orderId") Long orderId, @Param("status") Short status);

    List<OrderVo> selectByStatus(@Param("status") Short status, @Param("userId") Long userId);
}
