package com.troytan.ymcake.repository;

import com.troytan.ymcake.domain.ProductOrder;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_product_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orderId") Long orderId, @Param("productId") Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_product_order
     *
     * @mbg.generated
     */
    int insert(ProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_product_order
     *
     * @mbg.generated
     */
    ProductOrder selectByPrimaryKey(@Param("orderId") Long orderId, @Param("productId") Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_product_order
     *
     * @mbg.generated
     */
    List<ProductOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_product_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductOrder record);

    void insertBatch(List<ProductOrder> productOrders);
}