package com.troytan.ymcake.repository;

import com.troytan.ymcake.domain.Worker;
import java.util.List;

public interface WorkerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_worker
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer workerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_worker
     *
     * @mbg.generated
     */
    int insert(Worker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_worker
     *
     * @mbg.generated
     */
    Worker selectByPrimaryKey(Integer workerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_worker
     *
     * @mbg.generated
     */
    List<Worker> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_worker
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Worker record);
}