package com.troytan.ymcake.repository;

import com.troytan.ymcake.domain.Work;
import java.util.List;

public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_work
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_work
     *
     * @mbg.generated
     */
    int insert(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_work
     *
     * @mbg.generated
     */
    Work selectByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_work
     *
     * @mbg.generated
     */
    List<Work> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_work
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Work record);
}