package com.sgm.ymcake.domain;

public class ProductPic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_product_pic.PRODUCT_PIC_ID
     *
     * @mbg.generated
     */
    private Long productPicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_product_pic.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_product_pic.PRODUCT_ID
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_product_pic.PRODUCT_PIC_ID
     *
     * @return the value of tt_product_pic.PRODUCT_PIC_ID
     *
     * @mbg.generated
     */
    public Long getProductPicId() {
        return productPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_product_pic.PRODUCT_PIC_ID
     *
     * @param productPicId the value for tt_product_pic.PRODUCT_PIC_ID
     *
     * @mbg.generated
     */
    public void setProductPicId(Long productPicId) {
        this.productPicId = productPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_product_pic.img_url
     *
     * @return the value of tt_product_pic.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_product_pic.img_url
     *
     * @param imgUrl the value for tt_product_pic.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_product_pic.PRODUCT_ID
     *
     * @return the value of tt_product_pic.PRODUCT_ID
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_product_pic.PRODUCT_ID
     *
     * @param productId the value for tt_product_pic.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}