package com.sgm.ymcake.domain;

import java.math.BigDecimal;

public class Size {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_size.SIZE_ID
     *
     * @mbg.generated
     */
    private Long sizeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_size.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_size.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_size.PRODUCT_ID
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_size.SIZE_ID
     *
     * @return the value of tt_size.SIZE_ID
     *
     * @mbg.generated
     */
    public Long getSizeId() {
        return sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_size.SIZE_ID
     *
     * @param sizeId the value for tt_size.SIZE_ID
     *
     * @mbg.generated
     */
    public void setSizeId(Long sizeId) {
        this.sizeId = sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_size.description
     *
     * @return the value of tt_size.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_size.description
     *
     * @param description the value for tt_size.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_size.price
     *
     * @return the value of tt_size.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_size.price
     *
     * @param price the value for tt_size.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_size.PRODUCT_ID
     *
     * @return the value of tt_size.PRODUCT_ID
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_size.PRODUCT_ID
     *
     * @param productId the value for tt_size.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}