package com.sgm.ymcake.repository;

import com.sgm.ymcake.domain.Addr;
import java.util.List;

public interface AddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_addr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_addr
     *
     * @mbg.generated
     */
    int insert(Addr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_addr
     *
     * @mbg.generated
     */
    Addr selectByPrimaryKey(Long addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_addr
     *
     * @mbg.generated
     */
    List<Addr> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_addr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Addr record);
}