package com.sgm.ymcake.repository;

import com.sgm.ymcake.domain.Size;
import java.util.List;

public interface SizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_size
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_size
     *
     * @mbg.generated
     */
    int insert(Size record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_size
     *
     * @mbg.generated
     */
    Size selectByPrimaryKey(Long sizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_size
     *
     * @mbg.generated
     */
    List<Size> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Size record);
}